### ISSUE TITLE
Does it support XS 6.0?

### ISSUE THREAD

**Issue by naveensrinivasan** [hifi/monodevelop-justenoughvi#1]
The old VI option is removed from XS 6.0. Does this support 6.0? Is it also available in the addin site?

**Comment by hifi** [comment]
Honesty, I have no idea. I tried to use the addin built for 5.10 but apparently you can't load them as there's a version dependant reference to 5.10 assemblies. Also I can't build add-ins on XS because I couldn't find an easy way to get the development assemblies on Windows. 

I plan to publish it on the addin site once it has been tested enough by more people than me with different configurations. Possibly fixing some annoying bugs and adding more common navigational bindings before.

Removal of the old Vi option and the buggy behavior of it was a big motivator to start this addin and contribution are more than welcome when they are within the scope of the project. Anything related to NormalEditMode's behavior is a safe bet.

**Comment by hifi** [comment]
I have now had the possibility to have a look at MD/XS 6.0 and the required changes are major but doable and are the highest priority right now so that we have a Vi mode ready when it is released.

Thanks for bringing this to my attention.

**Comment by hifi** [comment]
Commit  f93548a407e1059eb4c00b093944eb9d72545681 ports the add-in to MD/XS 6.0.

**Comment by naveensrinivasan** [comment]
So I should be able to clone the repo and try this with XS 6.0?

**Comment by hifi** [comment]
Yes, this compiles and runs on XS 6.0 now.
